name: Playwright Tests

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * 1-5"
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    BASE_URL: ${{ vars.BASE_URL }}
    ENV: ${{ vars.ENV }}

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install dependencies
              run: npm ci

            - name: Run ESLint
              run: npx eslint .

            - name: Run Prettier
              run: npx prettier --check .

    e2e-ui-tests:
        runs-on: ubuntu-latest
        needs: lint-and-format
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout gh-pages branch to restore history
              uses: actions/checkout@v4
              with:
                  ref: gh-pages
                  path: gh-pages

            - name: Running tests on Chromium
              if: github.event_name == 'push' || github.event_name == 'pull_request'
              continue-on-error: true
              run: |
                  docker compose run e2e-ui-tests /bin/sh -c "ls -la \
                  && npm ci && npx playwright install && npx playwright test --project=chromium"

            - name: Running tests on all browsers
              if: github.event_name == 'schedule'
              continue-on-error: true
              run: |
                  docker compose run e2e-ui-tests /bin/sh -c "ls -la \
                  && npm ci && npx playwright install && npx playwright test"

            - name: Deploying report to GitHub pages
              uses: actions/upload-artifact@v4
              if: success()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
